// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	pool "github.com/gibmir/ion-go/pool"
	mock "github.com/stretchr/testify/mock"
)

// RequestFactoryEnvironment is an autogenerated mock type for the RequestFactoryEnvironment type
type RequestFactoryEnvironment struct {
	mock.Mock
}

// GetBufferPool provides a mock function with given fields:
func (_m *RequestFactoryEnvironment) GetBufferPool() *pool.BufferPool {
	ret := _m.Called()

	var r0 *pool.BufferPool
	if rf, ok := ret.Get(0).(func() *pool.BufferPool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pool.BufferPool)
		}
	}

	return r0
}

// GetDefaultUrl provides a mock function with given fields:
func (_m *RequestFactoryEnvironment) GetDefaultUrl() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHttpClient provides a mock function with given fields:
func (_m *RequestFactoryEnvironment) GetHttpClient() *http.Client {
	ret := _m.Called()

	var r0 *http.Client
	if rf, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}

	return r0
}

type mockConstructorTestingTNewRequestFactoryEnvironment interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequestFactoryEnvironment creates a new instance of RequestFactoryEnvironment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequestFactoryEnvironment(t mockConstructorTestingTNewRequestFactoryEnvironment) *RequestFactoryEnvironment {
	mock := &RequestFactoryEnvironment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
